[package]
name = "unit-vectors-thingy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.3"
fastrand = "2.0.1"
num_cpus = "1.16.0"
